version: '3.8'

services:
  mysql:
    image: mysql.latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: delgadoIgn
      MYSQL_PASSWORD: ignacio
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9090:9090
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      